name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Install the nightly toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - name: Set up cargo cache
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "8"
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install build-essential libssl-dev pkg-config libglib2.0-dev libgtk-3-dev libudev-dev
    - name: Check examples
      run: cargo check --examples
    - name: Lint
      run: cargo clippy --workspace -- -D warnings
    - name: Format
      run: cargo +nightly fmt --all --check -- --error-on-unformatted --unstable-features
    - name: Run tests
      run: |
        export RUSTFLAGS="-Cinstrument-coverage"
        export LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw'
        cargo test --workspace --exclude examples
    - name: Run doctests
      run: cargo test --workspace --doc
